---
- name: Ensure nginx SSL key pair directory exists
  file:
    path: "{{ nginx_ssl_dir }}"
    state: directory
    mode: 0755
  when: nginx_ssl_key_file | default(false)

- name: Copy SSL key and cert for nginx
  copy:
    src: "{{ item }}"
    dest: "{{ nginx_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ nginx_ssl_key_file }}"
    - "{{ nginx_ssl_certificate_file }}"
  notify:
    - restart nginx
    - restart_service nginx
  when:
    - nginx_ssl_key_file | default(false)
    - nginx_ssl_certificate_file | default(false)

- name: Copy nginx configuration file.
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx

- name: Remove default nginx vhost config file (if configured).
  file:
    path: "{{ nginx_default_vhost_path }}"
    state: absent
  when: nginx_remove_default_vhost | bool
  notify: restart nginx

- name: Ensure nginx_vhost_path exists.
  file:
    path: "{{ nginx_vhost_path }}"
    state: directory
    mode: 0755
  notify: restart nginx

- name: Add managed vhost config files.
  template:
    src: "vhost.j2"
    dest: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
    force: true
    owner: root
    group: root
    mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: restart nginx
