---
- name: restart nginx through systemd
  become: yes
  service:
    name: nginx
    state: restarted
  listen: "restart nginx"
    - not nginx_disable_install or nginx_instaled
    - not ansible_check_mode
