# Molecule managed

FROM {{ item.env.base_image }}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

{% if 'redhat' in item.name %}
RUN sed -i 's#proxy=url' /etc/dnf/dnf.conf
{% endif %}
